[Variables]


;====================WEATHER SETTINGS===========================


;latitude 
lat=22.5726
                 ;open google maps and search for your location's coordinates
;longitude
long=88.3639


;your openweathermap API Key...  hsssssh !! keep it secret !
APIKEY=


; 'metric' for celcius 'imperial' for Fahrenheit 
units=metric

; Letter for that particular temperature unit... do change it if you are changing the units :P
unitText=C


;================================================================


;NOTE : Skin specific related settings like Scale, color... can be changed by editing the [Variables] section of the skin code file.... 
